//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forex_Strategy_Trader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forex_Strategy_Trader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1day {
            get {
                object obj = ResourceManager.GetObject("_1day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_operation_buy {
            get {
                object obj = ResourceManager.GetObject("btn_operation_buy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_operation_close {
            get {
                object obj = ResourceManager.GetObject("btn_operation_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_operation_sell {
            get {
                object obj = ResourceManager.GetObject("btn_operation_sell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;lang&gt;
        ///  &lt;!-- Language (This will appear in the menu.) --&gt;
        ///  &lt;language&gt;Български&lt;/language&gt;
        ///  
        ///  &lt;!-- Credits --&gt;
        ///  &lt;translatedby&gt;Forex Software Ltd.&lt;/translatedby&gt;
        ///  &lt;website&gt;http://forexsb.com&lt;/website&gt;
        ///  &lt;corrections&gt;info@forexsb.com&lt;/corrections&gt;
        ///
        ///  &lt;!-- Common --&gt;
        ///  &lt;str&gt;&lt;main&gt;Yes&lt;/main&gt;&lt;alt&gt;Да&lt;/alt&gt;&lt;/str&gt;
        ///  &lt;str&gt;&lt;main&gt;No&lt;/main&gt;&lt;alt&gt;Не&lt;/alt&gt;&lt;/str&gt;
        ///  &lt;str&gt;&lt;main&gt;Ok&lt;/main&gt;&lt;alt&gt;Добре&lt;/alt&gt;&lt;/str&gt;
        ///  &lt;str&gt;&lt;main&gt;Default&lt;/main&gt;&lt;alt&gt;Подразбрано&lt;/alt&gt;&lt;/str&gt;
        ///  &lt;str&gt;&lt;main&gt;Cancel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap chart_auto_scroll {
            get {
                object obj = ResourceManager.GetObject("chart_auto_scroll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_cross {
            get {
                object obj = ResourceManager.GetObject("chart_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_dinfo_down {
            get {
                object obj = ResourceManager.GetObject("chart_dinfo_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_dinfo_up {
            get {
                object obj = ResourceManager.GetObject("chart_dinfo_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_dyninfo {
            get {
                object obj = ResourceManager.GetObject("chart_dyninfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_entry_points {
            get {
                object obj = ResourceManager.GetObject("chart_entry_points", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_grid {
            get {
                object obj = ResourceManager.GetObject("chart_grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_lots {
            get {
                object obj = ResourceManager.GetObject("chart_lots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_pos_price {
            get {
                object obj = ResourceManager.GetObject("chart_pos_price", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_refresh {
            get {
                object obj = ResourceManager.GetObject("chart_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_shift {
            get {
                object obj = ResourceManager.GetObject("chart_shift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_true_charts {
            get {
                object obj = ResourceManager.GetObject("chart_true_charts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_volume {
            get {
                object obj = ResourceManager.GetObject("chart_volume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_zoom_in {
            get {
                object obj = ResourceManager.GetObject("chart_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_zoom_out {
            get {
                object obj = ResourceManager.GetObject("chart_zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chat_icon {
            get {
                object obj = ResourceManager.GetObject("chat_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check_ind {
            get {
                object obj = ResourceManager.GetObject("check_ind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_blue {
            get {
                object obj = ResourceManager.GetObject("close_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_button {
            get {
                object obj = ResourceManager.GetObject("close_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;config&gt;
        ///  &lt;MAX_ENTRY_FILTERS&gt;4&lt;/MAX_ENTRY_FILTERS&gt;
        ///  &lt;MAX_EXIT_FILTERS&gt;2&lt;/MAX_EXIT_FILTERS&gt;
        ///  &lt;SIGMA_MODE_MAIN_CHART&gt;1&lt;/SIGMA_MODE_MAIN_CHART&gt;
        ///  &lt;SIGMA_MODE_SEPARATED_CHART&gt;5&lt;/SIGMA_MODE_SEPARATED_CHART&gt;
        ///  &lt;installed&gt;True&lt;/installed&gt;
        ///  &lt;showStartingTip&gt;True&lt;/showStartingTip&gt;
        ///  &lt;currentTipNumber&gt;-1&lt;/currentTipNumber&gt;
        ///  &lt;language&gt;English&lt;/language&gt;
        ///  &lt;gradientView&gt;True&lt;/gradientView&gt;
        ///  &lt;colorScheme&gt;Light Blue&lt;/colorScheme&gt;
        ///  &lt;multipleInstances&gt;False&lt;/multipleInstances&gt;
        ///  &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap connected {
            get {
                object obj = ResourceManager.GetObject("connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connected_no_ticks {
            get {
                object obj = ResourceManager.GetObject("connected_no_ticks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connection_wrong_ping {
            get {
                object obj = ResourceManager.GetObject("connection_wrong_ping", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connection_wrong_pings {
            get {
                object obj = ResourceManager.GetObject("connection_wrong_pings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contribute {
            get {
                object obj = ResourceManager.GetObject("contribute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap currency {
            get {
                object obj = ResourceManager.GetObject("currency", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custom_ind {
            get {
                object obj = ResourceManager.GetObject("custom_ind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custom_ind_forum {
            get {
                object obj = ResourceManager.GetObject("custom_ind_forum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap custom_indicators {
            get {
                object obj = ResourceManager.GetObject("custom_indicators", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap data_horizon {
            get {
                object obj = ResourceManager.GetObject("data_horizon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_arrow {
            get {
                object obj = ResourceManager.GetObject("down_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duplicate {
            get {
                object obj = ResourceManager.GetObject("duplicate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_translation {
            get {
                object obj = ResourceManager.GetObject("edit_translation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000-01-03	00:00	1.0078	1.0281	1.0049	1.0244	20088
        ///2000-01-04	00:00	1.0243	1.0343	1.0211	1.0290	5720
        ///2000-01-05	00:00	1.0291	1.0403	1.0280	1.0325	5981
        ///2000-01-06	00:00	1.0324	1.0415	1.0271	1.0323	7415
        ///2000-01-07	00:00	1.0325	1.0331	1.0252	1.0299	4142
        ///2000-01-10	00:00	1.0292	1.0311	1.0209	1.0251	4846
        ///2000-01-11	00:00	1.0251	1.0341	1.0242	1.0334	5078
        ///2000-01-12	00:00	1.0334	1.0369	1.0262	1.0306	5565
        ///2000-01-13	00:00	1.0306	1.0316	1.0235	1.0258	3117
        ///2000-01-14	00:00	1.0258	1.0276	1.0109	1.0124	8669
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EURUSD1440 {
            get {
                return ResourceManager.GetString("EURUSD1440", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expert_advisor {
            get {
                object obj = ResourceManager.GetObject("expert_advisor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forex_brokers {
            get {
                object obj = ResourceManager.GetObject("forex_brokers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forum_icon {
            get {
                object obj = ResourceManager.GetObject("forum_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;update&gt;
        ///  &lt;versions&gt;
        ///    &lt;release&gt;1040100&lt;/release&gt;
        ///    &lt;beta&gt;0&lt;/beta&gt;
        ///  &lt;/versions&gt;
        ///  &lt;links&gt;
        ///    &lt;link&gt;
        ///      &lt;text&gt;Forex Strategy Builder&lt;/text&gt;
        ///      &lt;url&gt;http://forexsb.com/&lt;/url&gt;
        ///      &lt;comment&gt;Free strategy tester, generator, optimizer...&lt;/comment&gt;
        ///    &lt;/link&gt;
        ///  &lt;/links&gt;
        ///  &lt;brokers&gt;
        ///    &lt;broker&gt;
        ///      &lt;text&gt;FastBrokers&lt;/text&gt;
        ///      &lt;url&gt;http://www.fastbrokers.com/index.php?bfd1bd24&lt;/url&gt;
        ///      &lt;comment&gt;Meta Trader platform.&lt;/comment&gt;
        ///    &lt;/broker&gt;
        ///    &lt;broker [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fst_update {
            get {
                return ResourceManager.GetString("fst_update", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fx_overview {
            get {
                object obj = ResourceManager.GetObject("fx_overview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap globe {
            get {
                object obj = ResourceManager.GetObject("globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hint {
            get {
                object obj = ResourceManager.GetObject("hint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap instr_edit {
            get {
                object obj = ResourceManager.GetObject("instr_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_bar_close {
            get {
                object obj = ResourceManager.GetObject("journal_bar_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_bar_open {
            get {
                object obj = ResourceManager.GetObject("journal_bar_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_blocked {
            get {
                object obj = ResourceManager.GetObject("journal_blocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_error {
            get {
                object obj = ResourceManager.GetObject("journal_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_import {
            get {
                object obj = ResourceManager.GetObject("journal_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_information {
            get {
                object obj = ResourceManager.GetObject("journal_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_ok {
            get {
                object obj = ResourceManager.GetObject("journal_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_start_trading {
            get {
                object obj = ResourceManager.GetObject("journal_start_trading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_stop_trading {
            get {
                object obj = ResourceManager.GetObject("journal_stop_trading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_system {
            get {
                object obj = ResourceManager.GetObject("journal_system", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_tick {
            get {
                object obj = ResourceManager.GetObject("journal_tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap journal_warning {
            get {
                object obj = ResourceManager.GetObject("journal_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lang {
            get {
                object obj = ResourceManager.GetObject("lang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lang_tools {
            get {
                object obj = ResourceManager.GetObject("lang_tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_translation {
            get {
                object obj = ResourceManager.GetObject("new_translation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap not_connected {
            get {
                object obj = ResourceManager.GetObject("not_connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap numb_br {
            get {
                object obj = ResourceManager.GetObject("numb_br", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap numb_gr {
            get {
                object obj = ResourceManager.GetObject("numb_gr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ord_buy {
            get {
                object obj = ResourceManager.GetObject("ord_buy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ord_buy_cancel {
            get {
                object obj = ResourceManager.GetObject("ord_buy_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ord_close {
            get {
                object obj = ResourceManager.GetObject("ord_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ord_sell {
            get {
                object obj = ResourceManager.GetObject("ord_sell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ord_sell_cancel {
            get {
                object obj = ResourceManager.GetObject("ord_sell_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overview {
            get {
                object obj = ResourceManager.GetObject("overview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap padlock_img {
            get {
                object obj = ResourceManager.GetObject("padlock_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap palette {
            get {
                object obj = ResourceManager.GetObject("palette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pie {
            get {
                object obj = ResourceManager.GetObject("pie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_buy {
            get {
                object obj = ResourceManager.GetObject("pos_buy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_close {
            get {
                object obj = ResourceManager.GetObject("pos_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_sell {
            get {
                object obj = ResourceManager.GetObject("pos_sell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pos_square {
            get {
                object obj = ResourceManager.GetObject("pos_square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prompt {
            get {
                object obj = ResourceManager.GetObject("prompt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap publish_strategy {
            get {
                object obj = ResourceManager.GetObject("publish_strategy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quick_start {
            get {
                object obj = ResourceManager.GetObject("quick_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap recalculate {
            get {
                object obj = ResourceManager.GetObject("recalculate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload_data {
            get {
                object obj = ResourceManager.GetObject("reload_data", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload_ind {
            get {
                object obj = ResourceManager.GetObject("reload_ind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap safety_first {
            get {
                object obj = ResourceManager.GetObject("safety_first", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as {
            get {
                object obj = ResourceManager.GetObject("save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap show_system_messages {
            get {
                object obj = ResourceManager.GetObject("show_system_messages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap show_ticks {
            get {
                object obj = ResourceManager.GetObject("show_ticks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_connect {
            get {
                return ResourceManager.GetStream("sound_connect", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_disconnect {
            get {
                return ResourceManager.GetStream("sound_disconnect", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_error {
            get {
                return ResourceManager.GetStream("sound_error", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_order_sent {
            get {
                return ResourceManager.GetStream("sound_order_sent", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sound_position_changed {
            get {
                return ResourceManager.GetStream("sound_position_changed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap str_export_as_ci {
            get {
                object obj = ResourceManager.GetObject("str_export_as_ci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_description {
            get {
                object obj = ResourceManager.GetObject("strategy_description", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_new {
            get {
                object obj = ResourceManager.GetObject("strategy_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_open {
            get {
                object obj = ResourceManager.GetObject("strategy_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_overview {
            get {
                object obj = ResourceManager.GetObject("strategy_overview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_publish {
            get {
                object obj = ResourceManager.GetObject("strategy_publish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_save {
            get {
                object obj = ResourceManager.GetObject("strategy_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_save_as {
            get {
                object obj = ResourceManager.GetObject("strategy_save_as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_settings {
            get {
                object obj = ResourceManager.GetObject("strategy_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_undo {
            get {
                object obj = ResourceManager.GetObject("strategy_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_zoom_in {
            get {
                object obj = ResourceManager.GetObject("strategy_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strategy_zoom_out {
            get {
                object obj = ResourceManager.GetObject("strategy_zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap symbol_editor {
            get {
                object obj = ResourceManager.GetObject("symbol_editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap synchronize {
            get {
                object obj = ResourceManager.GetObject("synchronize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_account {
            get {
                object obj = ResourceManager.GetObject("tab_account", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_chart {
            get {
                object obj = ResourceManager.GetObject("tab_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_journal {
            get {
                object obj = ResourceManager.GetObject("tab_journal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_operation {
            get {
                object obj = ResourceManager.GetObject("tab_operation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_status {
            get {
                object obj = ResourceManager.GetObject("tab_status", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_strategy {
            get {
                object obj = ResourceManager.GetObject("tab_strategy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tools {
            get {
                object obj = ResourceManager.GetObject("tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap up_arrow {
            get {
                object obj = ResourceManager.GetObject("up_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_translation {
            get {
                object obj = ResourceManager.GetObject("view_translation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
